# Generated by Django 5.1.5 on 2025-01-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
